async function Fsf_14_Web(moduleArg={}){var moduleRtn;var h=moduleArg,da=!!globalThis.window,k=!!globalThis.WorkerGlobalScope,l=k&&self.name?.startsWith("em-pthread");h.listen||(h.listen=a=>console.log(a));h.onError||(h.onError=a=>console.error(a));h.getRecommendedNnue=(a=0)=>ea(fa(a));h.setNnueBuffer=function(a,b=0){if(!a)throw Error("buf is null");if(0>=a.byteLength)throw Error(`${a.byteLength} bytes?`);const c=ha(a.byteLength);if(!c)throw Error(`could not allocate ${a.byteLength} bytes`);m();h.HEAPU8.set(a,c);ia(c,a.byteLength,b)};
h.uci=function(a){const b=ja(a)+1,c=ha(b);if(!c)throw Error(`Could not allocate ${b} bytes`);q(a,c,b);ka(c)};h.print=a=>h.listen?.(a);h.printErr=a=>h.onError?.(a);var la=[],ma=import.meta.url,na="",oa,pa;
if(da||k){try{na=(new URL(".",ma)).href}catch{}k&&(pa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});oa=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var qa=console.log.bind(console),t=console.error.bind(console),u,ra=!1,v;function m(){x.buffer!=y.buffer&&sa()}var ua,va,wa;
if(l){var xa=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.ka;if("load"===d){let e=[];self.onmessage=f=>e.push(f);wa=()=>{postMessage({ka:"loaded"});for(let f of e)a(f);self.onmessage=a};for(const f of c.Wa)if(!h[f]||h[f].proxy)h[f]=(...g)=>{postMessage({ka:"callHandler",Va:f,Ta:g})},"print"==f&&(qa=h[f]),"printErr"==f&&(t=h[f]);x=c.hb;sa();u=c.ib;ya();za()}else if("run"===d){Aa(c.ia);Ba(c.ia,0,0,1,0,0);Ca();Da(c.ia);xa||=!0;try{Ea(c.eb,c.Ba)}catch(e){if("unwind"!=
e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?xa&&Fa():d&&(t(`worker: received unknown command ${d}`),t(c)))}catch(e){throw Ga(),e;}}self.onmessage=a}var y,Ha,Ia,z,A,Ja,B,Ka=!1,La=!1;function sa(){var a=x.buffer;y=new Int8Array(a);Ia=new Int16Array(a);h.HEAPU8=Ha=new Uint8Array(a);new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);new Float32Array(a);Ja=new Float64Array(a);B=new BigInt64Array(a);new BigUint64Array(a)}
function Ma(){Ka=!0;l?wa():(h.noFSInit||Na||(Na=!0,Oa("/dev/tty","/dev/stdin"),Oa("/dev/tty","/dev/stdout"),Oa("/dev/tty1","/dev/stderr"),Pa("/dev/stdin",0),Pa("/dev/stdout",1),Pa("/dev/stderr",1)),C.D(),Qa=!1)}function Ra(a){a="Aborted("+a+")";t(a);ra=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");va?.(a);throw a;}var Sa;
async function Ta(a){try{var b=await oa(a);return new Uint8Array(b)}catch{}if(pa)a=pa(a);else throw"both async and sync fetching of the wasm failed";return a}async function Ua(a,b){try{var c=await Ta(a);return await WebAssembly.instantiate(c,b)}catch(d){t(`failed to asynchronously prepare wasm: ${d}`),Ra(d)}}
async function Va(a){var b=Sa;try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){t(`wasm streaming compile failed: ${d}`),t("falling back to ArrayBuffer instantiation")}return Ua(b,a)}function Wa(){Xa={A:Ya,e:Za,u:$a,w:ab,n:bb,j:cb,z:db,C:eb,p:fb,f:gb,i:Da,h:hb,q:ib,r:jb,B:kb,g:lb,m:mb,b:nb,y:ob,v:pb,k:qb,l:rb,c:sb,d:tb,t:ub,s:vb,x:wb,a:x,o:xb};return{a:Xa}}
async function ya(){function a(d,e){C=d.exports;yb.push(C.J);d=C;h._main=d.E;h.__Z10js_getlinev=d.F;ka=h._uci=d.G;ia=h._setNnueBuffer=d.H;fa=h._getRecommendedNnue=d.I;zb=d.K;Ab=h.__emscripten_proxy_main=d.L;Bb=d.N;Ba=d.O;Ga=d.P;Cb=d.Q;ha=h._malloc=d.R;Db=d.S;Eb=d.T;Fb=d.U;Gb=d.V;Hb=d.W;Ib=d.X;Jb=d.Y;Kb=d.Z;Lb=d._;Mb=d.M;u=e;return C}var b=Wa();if(h.instantiateWasm)return new Promise(d=>{h.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(l){var c=new WebAssembly.Instance(u,Wa());return a(c,u)}Sa??=h.locateFile?
h.locateFile?h.locateFile("fsf_14.wasm",na):na+"fsf_14.wasm":(new URL("fsf_14.wasm",import.meta.url)).href;return function(d){return a(d.instance,d.module)}(await Va(b))}class Nb{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ob=a=>{a.terminate();a.onmessage=()=>{}},Pb=[],Rb=a=>{if(0==F.length){if(h.mainScriptUrlOrBlob){var b=h.mainScriptUrlOrBlob;"string"!=typeof b&&(b=URL.createObjectURL(b));b=new Worker(b,{type:"module",name:"em-pthread"})}else b=new Worker(new URL("fsf_14.js",import.meta.url),{type:"module",name:"em-pthread"});F.push(b);Qb()}b=F.pop();if(!b)return 6;G.push(b);H[a.ia]=b;b.ia=a.ia;b.postMessage({ka:"run",eb:a.cb,Ba:a.Ba,ia:a.ia},a.Ra);return 0},I=0,pb=()=>0<I,J=(a,b,...c)=>{for(var d=
2*c.length,e=Lb(),f=Kb(8*d),g=f>>3,n=0;n<c.length;n++){var r=c[n];"bigint"==typeof r?((m(),B)[g+2*n]=1n,(m(),B)[g+2*n+1]=r):((m(),B)[g+2*n]=0n,(m(),Ja)[g+2*n+1]=r)}a=Db(a,0,d,f,b);Jb(e);return a};function xb(a){if(l)return J(0,1,a);v=a;0<I||(Sb(),ra=!0);throw new Nb(a);}function Tb(a){if(l)return J(1,0,a);--I;sb(a)}
var sb=a=>{v=a;if(l)throw Tb(a),"unwind";if(!(0<I||l)){Bb();Na=!1;Cb(0);for(var b of K)b&&Ub(b);Sb();La=!0}xb(a)},F=[],G=[],yb=[],H={},Sb=()=>{for(var a of G)Ob(a);for(a of F)Ob(a);F=[];G=[];H={}},Vb=a=>{var b=a.ia;delete H[b];F.push(a);G.splice(G.indexOf(a),1);a.ia=0;Eb(b)};function Ca(){yb.forEach(a=>a())}
var Qb=()=>{var a=F[0];new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.ka;if(g.Aa&&g.Aa!=zb()){var n=H[g.Aa];n?n.postMessage(g,g.Ra):t(`Internal error! Worker sent a message "${f}" to target pthread ${g.Aa}, but that thread no longer exists!`)}else if("checkMailbox"===f)Fa();else if("spawnThread"===f)Rb(g);else if("cleanupThread"===f)Wb(()=>{Vb(H[g.fb])});else if("loaded"===f)a.loaded=!0,b(a);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===f)h[g.Va](...g.Ta);else f&&t(`worker sent an unknown command ${f}`)};
a.onerror=f=>{t(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({ka:"load",Wa:c,hb:x,ib:u})})};function Aa(a){var b=(m(),A)[a+52>>2];a=(m(),A)[a+56>>2];Ib(b,b-a);Jb(b)}var Xb=[],Ea=(a,b)=>{I=0;var c=Xb[a];c||(Xb[a]=c=Mb.get(a));a=c(b);0<I?v=a:Fb(a)},x;function Yb(a,b,c,d){return l?J(2,1,a,b,c,d):Ya(a,b,c,d)}
var Ya=(a,b,c,d)=>{if(!globalThis.SharedArrayBuffer)return 6;var e=[];if(l&&0===e.length)return Yb(a,b,c,d);a={cb:c,ia:a,Ba:d,Ra:e};return l?(a.ka="spawnThread",postMessage(a,e),0):Rb(a)},M=()=>{var a=(m(),z)[+L>>2];L+=4;return a},Zb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},$b=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Zb(a.split("/").filter(d=>!!d),!b).join("/"))||
b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},ac=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},bc=()=>a=>a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),cc=a=>{(cc=bc())(a)},dc=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=
Zb(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},ec=globalThis.TextDecoder&&new TextDecoder,O=(a,b=0,c,d)=>{var e=b;c=e+c;if(d)d=c;else{for(;a[e]&&!(e>=c);)++e;d=e}if(16<d-b&&a.buffer&&ec)return ec.decode(a.buffer instanceof ArrayBuffer?a.subarray(b,d):a.slice(b,d));for(e="";b<d;)if(c=a[b++],c&128){var f=a[b++]&63;if(192==(c&224))e+=String.fromCharCode((c&31)<<6|f);else{var g=a[b++]&63;c=224==(c&240)?(c&15)<<12|f<<6|g:(c&7)<<18|f<<12|g<<6|a[b++]&63;65536>c?e+=String.fromCharCode(c):
(c-=65536,e+=String.fromCharCode(55296|c>>10,56320|c&1023))}}else e+=String.fromCharCode(c);return e},fc=[],ja=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},gc=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>
6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},hc=[];function ic(a,b){hc[a]={input:[],output:[],ma:b};jc(a,kc)}
var kc={open(a){var b=hc[a.node.ya];if(!b)throw new P(43);a.ca=b;a.seekable=!1},close(a){a.ca.ma.va(a.ca)},va(a){a.ca.ma.va(a.ca)},read(a,b,c,d){if(!a.ca||!a.ca.ma.Ka)throw new P(60);for(var e=0,f=0;f<d;f++){try{var g=a.ca.ma.Ka(a.ca)}catch(n){throw new P(29);}if(void 0===g&&0===e)throw new P(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.qa=Date.now());return e},write(a,b,c,d){if(!a.ca||!a.ca.ma.Ga)throw new P(60);try{for(var e=0;e<d;e++)a.ca.ma.Ga(a.ca,b[c+e])}catch(f){throw new P(29);
}d&&(a.node.fa=a.node.ea=Date.now());return e}},lc={Ka(){a:{if(!fc.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(ja(a)+1);a=gc(a,b,0,b.length);b.length=a;fc=b}b=fc.shift()}return b},Ga(a,b){null===b||10===b?(qa(O(a.output)),a.output=[]):0!=b&&a.output.push(b)},va(a){0<a.output?.length&&(qa(O(a.output)),a.output=[])},Ya(){return{nb:25856,pb:5,mb:191,ob:35387,lb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0]}},Za(){return 0},$a(){return[24,80]}},mc={Ga(a,b){null===b||10===b?(t(O(a.output)),a.output=[]):0!=b&&a.output.push(b)},va(a){0<a.output?.length&&(t(O(a.output)),a.output=[])}},Q={ha:null,la(){return Q.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new P(63);Q.ha||(Q.ha={dir:{node:{pa:Q.ba.pa,ja:Q.ba.ja,sa:Q.ba.sa,wa:Q.ba.wa,Pa:Q.ba.Pa,Sa:Q.ba.Sa,Qa:Q.ba.Qa,Ha:Q.ba.Ha,za:Q.ba.za},stream:{ga:Q.$.ga}},file:{node:{pa:Q.ba.pa,ja:Q.ba.ja},
stream:{ga:Q.$.ga,read:Q.$.read,write:Q.$.write,Ma:Q.$.Ma,Oa:Q.$.Oa}},link:{node:{pa:Q.ba.pa,ja:Q.ba.ja,ta:Q.ba.ta},stream:{}},Ja:{node:{pa:Q.ba.pa,ja:Q.ba.ja},stream:nc}});c=oc(a,b,c,d);16384===(c.mode&61440)?(c.ba=Q.ha.dir.node,c.$=Q.ha.dir.stream,c.aa={}):32768===(c.mode&61440)?(c.ba=Q.ha.file.node,c.$=Q.ha.file.stream,c.da=0,c.aa=null):40960===(c.mode&61440)?(c.ba=Q.ha.link.node,c.$=Q.ha.link.stream):8192===(c.mode&61440)&&(c.ba=Q.ha.Ja.node,c.$=Q.ha.Ja.stream);c.qa=c.fa=c.ea=Date.now();a&&(a.aa[b]=
c,a.qa=a.fa=a.ea=c.qa);return c},tb(a){return a.aa?a.aa.subarray?a.aa.subarray(0,a.da):new Uint8Array(a.aa):new Uint8Array(0)},ba:{pa(a){var b={};b.qb=8192===(a.mode&61440)?a.id:1;b.vb=a.id;b.mode=a.mode;b.wb=1;b.uid=0;b.ub=0;b.ya=a.ya;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.da:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.qa=new Date(a.qa);b.fa=new Date(a.fa);b.ea=new Date(a.ea);b.Ua=4096;b.kb=Math.ceil(b.size/b.Ua);return b},ja(a,b){for(var c of["mode","atime",
"mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.da!=b&&(0==b?(a.aa=null,a.da=0):(c=a.aa,a.aa=new Uint8Array(b),c&&a.aa.set(c.subarray(0,Math.min(b,a.da))),a.da=b)))},sa(){Q.Ca||(Q.Ca=new P(44),Q.Ca.stack="<generic error, no stack>");throw Q.Ca;},wa(a,b,c,d){return Q.createNode(a,b,c,d)},Pa(a,b,c){try{var d=pc(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.aa)throw new P(55);e=qc(d.parent.id,d.name);if(R[e]===d)R[e]=d.ra;else for(e=R[e];e;){if(e.ra===d){e.ra=d.ra;
break}e=e.ra}}delete a.parent.aa[a.name];b.aa[c]=a;a.name=c;b.ea=b.fa=a.parent.ea=a.parent.fa=Date.now()},Sa(a,b){delete a.aa[b];a.ea=a.fa=Date.now()},Qa(a,b){var c=pc(a,b),d;for(d in c.aa)throw new P(55);delete a.aa[b];a.ea=a.fa=Date.now()},Ha(a){return[".","..",...Object.keys(a.aa)]},za(a,b,c){a=Q.createNode(a,b,41471,0);a.link=c;return a},ta(a){if(40960!==(a.mode&61440))throw new P(28);return a.link}},$:{read(a,b,c,d,e){var f=a.node.aa;if(e>=a.node.da)return 0;a=Math.min(a.node.da-e,d);if(8<a&&
f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===(m(),y).buffer&&(f=!1);if(!d)return 0;a=a.node;a.fa=a.ea=Date.now();if(b.subarray&&(!a.aa||a.aa.subarray)){if(f)return a.aa=b.subarray(c,c+d),a.da=d;if(0===a.da&&0===e)return a.aa=b.slice(c,c+d),a.da=d;if(e+d<=a.da)return a.aa.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.aa?a.aa.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.aa,a.aa=new Uint8Array(f),
0<a.da&&a.aa.set(g.subarray(0,a.da),0));if(a.aa.subarray&&b.subarray)a.aa.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.aa[e+f]=b[c+f];a.da=Math.max(a.da,e+d);return d},ga(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.da);if(0>b)throw new P(28);return b},Ma(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new P(43);a=a.node.aa;if(e&2||!a||a.buffer!==(m(),y).buffer){d=!0;Ra();e=void 0;if(!e)throw new P(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);(m(),y).set(a,e)}}else d=!1,e=a.byteOffset;return{yb:e,jb:d}},Oa(a,b,c,d){Q.$.write(a,b,0,d,c,!1);return 0}}},rc=a=>{var b=0;a&&(b|=365);return b},sc=0,tc=null,uc={},K=[],vc=1,R=null,Na=!1,Qa=!0,P=class{name="ErrnoError";constructor(a){this.na=a}},wc=class{ua={};node=null;get flags(){return this.ua.flags}set flags(a){this.ua.flags=a}get position(){return this.ua.position}set position(a){this.ua.position=a}},xc=class{ba={};$={};xa=null;constructor(a,b,c,d){a||=this;this.parent=a;this.la=a.la;
this.id=vc++;this.name=b;this.mode=c;this.ya=d;this.qa=this.fa=this.ea=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function S(a,b={}){if(!a)throw new P(44);b.Ea??(b.Ea=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(n=>!!n);for(var d=tc,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=ac(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=$b(e+"/"+a[f]);try{d=pc(d,a[f])}catch(n){if(44===n?.na&&g&&b.bb)return{path:e};throw n;}!d.xa||g&&!b.Ea||(d=d.xa.root);if(40960===(d.mode&61440)&&(!g||b.Da)){if(!d.ba.ta)throw new P(52);
d=d.ba.ta(d);"/"===d.charAt(0)||(d=ac(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new P(32);}function qc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length}function pc(a,b){var c=16384===(a.mode&61440)?(c=yc(a,"x"))?c:a.ba.sa?0:2:54;if(c)throw new P(c);for(c=R[qc(a.id,b)];c;c=c.ra){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ba.sa(a,b)}
function oc(a,b,c,d){a=new xc(a,b,c,d);b=qc(a.parent.id,a.name);a.ra=R[b];return R[b]=a}function zc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function yc(a,b){if(Qa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ac(a,b){if(16384!==(a.mode&61440))return 54;try{return pc(a,b),20}catch(c){}return yc(a,"wx")}function T(a){a=K[a];if(!a)throw new P(8);return a}
function Bc(a,b=-1){a=Object.assign(new wc,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!K[b])break a;throw new P(33);}a.oa=b;return K[b]=a}function Cc(a,b=-1){a=Bc(a,b);a.$?.sb?.(a);return a}function Dc(a,b){var c=null?.$.ja,d=c?null:a;c??=a.ba.ja;if(!c)throw new P(63);c(d,b)}var nc={open(a){a.$=uc[a.node.ya].$;a.$.open?.(a)},ga(){throw new P(70);}};function jc(a,b){uc[a]={$:b}}
function Ec(a,b){var c="/"===b;if(c&&tc)throw new P(10);if(!c&&b){var d=S(b,{Ea:!1});b=d.path;d=d.node;if(d.xa)throw new P(10);if(16384!==(d.mode&61440))throw new P(54);}b={type:a,xb:{},Na:b,ab:[]};a=a.la(b);a.la=b;b.root=a;c?tc=a:d&&(d.xa=b,d.la&&d.la.ab.push(b))}function Fc(a,b,c){var d=S(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new P(28);if("."===a||".."===a)throw new P(20);var e=Ac(d,a);if(e)throw new P(e);if(!d.ba.wa)throw new P(63);return d.ba.wa(d,a,b,c)}
function U(a){return Fc(a,16895,0)}function Gc(a,b,c){"undefined"==typeof c&&(c=b,b=438);Fc(a,b|8192,c)}function Oa(a,b){if(!dc(a))throw new P(44);var c=S(b,{parent:!0}).node;if(!c)throw new P(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Ac(c,b);if(d)throw new P(d);if(!c.ba.za)throw new P(63);c.ba.za(c,b,a)}
function Pa(a,b,c=438){if(""===a)throw new P(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");var f=S(a,{Da:!(b&131072),bb:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new P(20);}else{if(e)throw new P(31);d=Fc(a,c|511,0);f=!0}if(!d)throw new P(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&
61440))throw new P(54);if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==zc(b)||b&576)?31:yc(d,zc(b)):44))throw new P(e);if(b&512&&!f){e=d;e="string"==typeof e?S(e,{Da:!0}).node:e;if(16384===(e.mode&61440))throw new P(31);if(32768!==(e.mode&61440))throw new P(28);if(a=yc(e,"w"))throw new P(a);Dc(e,{size:0,timestamp:Date.now()})}a:for(e=d;;){if(e===e.parent){e=e.la.Na;var g=g?"/"!==e[e.length-1]?`${e}/${g}`:e+g:e;break a}g=g?`${e.name}/${g}`:e.name;e=e.parent}b=Bc({node:d,path:g,
flags:b&-131713,seekable:!0,position:0,$:d.$,gb:[],error:!1});b.$.open&&b.$.open(b);f&&(c&=511,d="string"==typeof d?S(d,{Da:!0}).node:d,Dc(d,{mode:c&4095|d.mode&-4096,ea:Date.now(),rb:void 0}));return b}function Ub(a){if(null===a.oa)throw new P(8);a.Fa&&(a.Fa=null);try{a.$.close&&a.$.close(a)}catch(b){throw b;}finally{K[a.oa]=null}a.oa=null}
function Hc(a,b,c){if(null===a.oa)throw new P(8);if(!a.seekable||!a.$.ga)throw new P(70);if(0!=c&&1!=c&&2!=c)throw new P(28);a.position=a.$.ga(a,b,c);a.gb=[]}
function V(a,b){a=$b("/dev/"+a);var c=rc(!!b);V.La??(V.La=64);var d=V.La++<<8|0;jc(d,{open(e){e.seekable=!1},close(){(void 0)?.buffer?.length&&(void 0)(10)},read(e,f,g,n){for(var r=0,p=0;p<n;p++){try{var w=b()}catch(ta){throw new P(29);}if(void 0===w&&0===r)throw new P(6);if(null===w||void 0===w)break;r++;f[g+p]=w}r&&(e.node.qa=Date.now());return r},write(e,f,g,n){for(var r=0;r<n;r++)try{(void 0)(f[g+r])}catch(p){throw new P(29);}n&&(e.node.fa=e.node.ea=Date.now());return r}});Gc(a,c,d)}
var W={},ea=(a,b,c)=>a?O((m(),Ha),a,b,c):"",L=void 0;function Za(a,b,c){if(l)return J(3,1,a,b,c);L=c;try{var d=T(a);switch(b){case 0:var e=M();if(0>e)break;for(;K[e];)e++;return Cc(d,e).oa;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=M(),d.flags|=e,0;case 12:return e=M(),(m(),Ia)[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof W||"ErrnoError"!==f.name)throw f;return-f.na}}
function $a(a,b,c){if(l)return J(4,1,a,b,c);L=c;try{var d=T(a);switch(b){case 21509:return d.ca?0:-59;case 21505:if(!d.ca)return-59;if(d.ca.ma.Ya){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=M();(m(),z)[e>>2]=25856;(m(),z)[e+4>>2]=5;(m(),z)[e+8>>2]=191;(m(),z)[e+12>>2]=35387;for(var f=0;32>f;f++)(m(),y)[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.ca?0:-59;case 21506:case 21507:case 21508:if(!d.ca)return-59;if(d.ca.ma.Za)for(e=M(),m(),
m(),m(),m(),a=[],f=0;32>f;f++)a.push((m(),y)[e+f+17]);return 0;case 21519:if(!d.ca)return-59;e=M();return(m(),z)[e>>2]=0;case 21520:return d.ca?-28:-59;case 21537:case 21531:e=M();if(!d.$.Xa)throw new P(59);return d.$.Xa(d,b,e);case 21523:if(!d.ca)return-59;d.ca.ma.$a&&(f=[24,80],e=M(),(m(),Ia)[e>>1]=f[0],(m(),Ia)[e+2>>1]=f[1]);return 0;case 21524:return d.ca?0:-59;case 21515:return d.ca?0:-59;default:return-28}}catch(g){if("undefined"==typeof W||"ErrnoError"!==g.name)throw g;return-g.na}}
function ab(a,b,c,d){if(l)return J(5,1,a,b,c,d);L=d;try{b=ea(b);var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":T(a).path;if(0==e.length)throw new P(44);b=f+"/"+e}var g=d?M():0;return Pa(b,c,g).oa}catch(n){if("undefined"==typeof W||"ErrnoError"!==n.name)throw n;return-n.na}}
var bb=()=>Ra(""),cb=a=>{Ba(a,!k,1,!da,3145728,!1);Ca()},Ic=a=>{if(!(a instanceof Nb||"unwind"==a))throw a;},Wb=a=>{if(!La&&!ra)try{if(a(),!(La||0<I))try{l?zb()&&Fb(v):sb(v)}catch(b){Ic(b)}}catch(b){Ic(b)}},Da=a=>{Atomics.waitAsync&&(Atomics.waitAsync((m(),z),a>>2,a).value.then(Fa),a+=128,Atomics.store((m(),z),a>>2,1))},Fa=()=>Wb(()=>{var a=zb();a&&(Da(a),Hb())}),db=(a,b)=>{a==b?setTimeout(Fa):l?postMessage({Aa:a,ka:"checkMailbox"}):(a=H[a])&&a.postMessage({ka:"checkMailbox"})},Jc=[],eb=(a,b,c,d,
e)=>{d/=2;Jc.length=d;b=e>>3;for(c=0;c<d;c++)(m(),B)[b+2*c]?Jc[c]=(m(),B)[b+2*c+1]:Jc[c]=(m(),Ja)[b+2*c+1];return(0,Kc[a])(...Jc)},fb=()=>{I=0},gb=a=>{l?postMessage({ka:"cleanupThread",fb:a}):Vb(H[a])},hb=()=>{},X={},nb=()=>performance.timeOrigin+performance.now();function ib(a,b){if(l)return J(6,1,a,b);X[a]&&(clearTimeout(X[a].id),delete X[a]);if(!b)return 0;var c=setTimeout(()=>{delete X[a];Wb(()=>Gb(a,performance.timeOrigin+performance.now()))},b);X[a]={id:c,zb:b};return 0}
var q=(a,b,c)=>gc(a,(m(),Ha),b,c),jb=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var g=Math.max(f,e);(m(),A)[a>>2]=60*g;(m(),z)[b>>2]=Number(f!=e);b=n=>{var r=Math.abs(n);return`UTC${0<=n?"-":"+"}${String(Math.floor(r/60)).padStart(2,"0")}${String(r%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(q(a,c,17),q(b,d,17)):(q(a,d,17),q(b,c,17))},Lc=1;
function kb(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(Lc)a=performance.timeOrigin+performance.now();else return 52;a=Math.round(1E6*a);(m(),B)[c>>3]=BigInt(a);return 0}
var Y=()=>{Y.Ia||(Y.Ia={});Y.Ia["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(Y.Ia["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,t("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"))},lb=()=>{k||(Y(),Ra("Blocking on the main thread is not allowed by default. See https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"))},
mb=()=>{I+=1;throw"unwind";},ob=a=>{var b=(m(),Ha).length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-x.buffer.byteLength+65535)/65536|0;try{x.grow(d);sa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Mc={},Oc=()=>{if(!Nc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-",
"_")+".UTF-8",_:"./this.program"},b;for(b in Mc)void 0===Mc[b]?delete a[b]:a[b]=Mc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Nc=c}return Nc},Nc;function qb(a,b){if(l)return J(7,1,a,b);var c=0,d=0,e;for(e of Oc()){var f=b+c;(m(),A)[a+d>>2]=f;c+=q(e,f,Infinity)+1;d+=4}return 0}function rb(a,b){if(l)return J(8,1,a,b);var c=Oc();(m(),A)[a>>2]=c.length;a=0;for(var d of c)a+=ja(d)+1;(m(),A)[b>>2]=a;return 0}
function tb(a){if(l)return J(9,1,a);try{var b=T(a);Ub(b);return 0}catch(c){if("undefined"==typeof W||"ErrnoError"!==c.name)throw c;return c.na}}
function ub(a,b,c,d){if(l)return J(10,1,a,b,c,d);try{a:{var e=T(a);a=b;for(var f,g=b=0;g<c;g++){var n=(m(),A)[a>>2],r=(m(),A)[a+4>>2];a+=8;var p=e,w=(m(),y),ta=n,Z=r,D=f;if(0>Z||0>D)throw new P(28);if(null===p.oa)throw new P(8);if(1===(p.flags&2097155))throw new P(8);if(16384===(p.node.mode&61440))throw new P(31);if(!p.$.read)throw new P(28);var aa="undefined"!=typeof D;if(!aa)D=p.position;else if(!p.seekable)throw new P(70);var ba=p.$.read(p,w,ta,Z,D);aa||(p.position+=ba);var E=ba;if(0>E){var ca=
-1;break a}b+=E;if(E<r)break;"undefined"!=typeof f&&(f+=E)}ca=b}(m(),A)[d>>2]=ca;return 0}catch(N){if("undefined"==typeof W||"ErrnoError"!==N.name)throw N;return N.na}}function vb(a,b,c,d){if(l)return J(11,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=T(a);Hc(e,b,c);(m(),B)[d>>3]=BigInt(e.position);e.Fa&&0===b&&0===c&&(e.Fa=null);return 0}catch(f){if("undefined"==typeof W||"ErrnoError"!==f.name)throw f;return f.na}}
function wb(a,b,c,d){if(l)return J(12,1,a,b,c,d);try{a:{var e=T(a);a=b;for(var f,g=b=0;g<c;g++){var n=(m(),A)[a>>2],r=(m(),A)[a+4>>2];a+=8;var p=e,w=(m(),y),ta=n,Z=r,D=f;if(0>Z||0>D)throw new P(28);if(null===p.oa)throw new P(8);if(0===(p.flags&2097155))throw new P(8);if(16384===(p.node.mode&61440))throw new P(31);if(!p.$.write)throw new P(28);p.seekable&&p.flags&1024&&Hc(p,0,2);var aa="undefined"!=typeof D;if(!aa)D=p.position;else if(!p.seekable)throw new P(70);var ba=p.$.write(p,w,ta,Z,D,void 0);
aa||(p.position+=ba);var E=ba;if(0>E){var ca=-1;break a}b+=E;if(E<r)break;"undefined"!=typeof f&&(f+=E)}ca=b}(m(),A)[d>>2]=ca;return 0}catch(N){if("undefined"==typeof W||"ErrnoError"!==N.name)throw N;return N.na}}R=Array(4096);Ec(Q,"/");U("/tmp");U("/home");U("/home/web_user");
(function(){U("/dev");jc(259,{read:()=>0,write:(d,e,f,g)=>g,ga:()=>0});Gc("/dev/null",259);ic(1280,lc);ic(1536,mc);Gc("/dev/tty",1280);Gc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(cc(a),b=a.byteLength);return a[--b]};V("random",c);V("urandom",c);U("/dev/shm");U("/dev/shm/tmp")})();
(function(){U("/proc");var a=U("/proc/self");U("/proc/self/fd");Ec({la(){var b=oc(a,"fd",16895,73);b.$={ga:Q.$.ga};b.ba={sa(c,d){c=+d;var e=T(c);c={parent:null,la:{Na:"fake"},ba:{ta:()=>e.path},id:c+1};return c.parent=c},Ha(){return Array.from(K.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();l||(h.wasmMemory?x=h.wasmMemory:x=new WebAssembly.Memory({initial:1024,maximum:32768,shared:!0}),sa());h.print&&(qa=h.print);h.printErr&&(t=h.printErr);
h.UTF8ToString=ea;h.stringToUTF8=q;var Kc=[xb,Tb,Yb,Za,$a,ab,ib,qb,rb,tb,ub,vb,wb],ka,ia,fa,zb,Ab,Bb,Ba,Ga,Cb,ha,Db,Eb,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Mb,Xa;function Pc(a=[]){var b=Ab;I+=1;a.unshift("./this.program");var c=a.length,d=Kb(4*(c+1)),e=d;a.forEach(g=>{var n=(m(),A),r=e>>2,p=ja(g)+1,w=Kb(p);q(g,w,p);n[r]=w;e+=4});(m(),A)[e>>2]=0;try{var f=b(c,d);sb(f,!0)}catch(g){Ic(g)}}
function za(){if(!(0<sc))if(l)ua?.(h),Ma();else{for(var a=Pb;0<a.length;)a.shift()(h);0<sc||(h.calledRun=!0,ra||(Ma(),ua?.(h),Pc(la)))}}var C;l||(C=await (ya()),za());Ka?moduleRtn=h:moduleRtn=new Promise((a,b)=>{ua=a;va=b});
;return moduleRtn}export default Fsf_14_Web;var isPthread=globalThis.self?.name?.startsWith("em-pthread");isPthread&&Fsf_14_Web();
